# Python Crime project analysis - Cleaning phase
This notebook contains all the preprocessing steps and other processes went before analysis

**NOTE: PLEASE RUN EACH CELL IN TURN OTHERWISE THIS WILL NOT WORK** <br>
**NOTE: THIS TAKES UP A LOT OF MEMORY AND CAN TAKE A WHILE TO RUN**

Import the necessary libraries and if not installed install them

In [ ]:
! pip install pandas

Requirement already satisfied: pandas in C:\Users\mkyas\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\mkyas\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\mkyas\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\mkyas\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\mkyas\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: matplotlib in C:\Users\mkyas\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\mkyas\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\mkyas\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\mkyas\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (4.62.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\mkyas\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in C:\Users\mkyas\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (2.4.3)
Requirement already satisfied: packaging>=20.0 in C:\Users\mkyas\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in C:\Users\mkyas\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in C:\Users\mkyas\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\mkyas\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in C:\Users\mkyas\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: geopandas in C:\Users\mkyas\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.1.3)
Requirement already satisfied: numpy>=1.24 in C:\Users\mkyas\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from geopandas) (2.4.3)
Requirement already satisfied: pyogrio>=0.7.2 in C:\Users\mkyas\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from geopandas) (0.12.1)
Requirement already satisfied: packaging in C:\Users\mkyas\AppData\Roaming\Python\Python314\site-packages (from geopandas) (26.0)
Requirement already satisfied: pandas>=2.0.0 in C:\Users\mkyas\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from geopandas) (3.0.1)
Requirement already satisfied: pyproj>=3.5.0 in C:\Users\mkyas\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from geopandas) (3.7.2)
Requirement already satisfied: shapely>=2.0.0 in C:\Users\mkyas\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from geopandas) (2.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\mkyas\AppData\Roaming\Python\Python314\site-packages (from pandas>=2.0.0->geopandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\mkyas\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas>=2.0.0->geopandas) (2025.3)
Requirement already satisfied: certifi in C:\Users\mkyas\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pyogrio>=0.7.2->geopandas) (2026.2.25)
Requirement already satisfied: six>=1.5 in C:\Users\mkyas\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->geopandas) (1.17.0)
Collecting cartopy
  Downloading cartopy-0.25.0.tar.gz (10.8 MB)
     ---------------------------------------- 0.0/10.8 MB ? eta -:--:--
     ---------------------------------------- 0.0/10.8 MB ? eta -:--:--
     ------ --------------------------------- 1.8/10.8 MB 10.6 MB/s eta 0:00:01
     -------------- ------------------------- 3.9/10.8 MB 10.4 MB/s eta 0:00:01
     ------------------------ --------------- 6.6/10.8 MB 10.8 MB/s eta 0:00:01
     ---------------------------------- ----- 9.2/10.8 MB 11.2 MB/s eta 0:00:01
     ---------------------------------------- 10.8/10.8 MB 10.6 MB/s  0:00:01
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: numpy>=1.23 in C:\Users\mkyas\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from cartopy) (2.4.3)
Requirement already satisfied: matplotlib>=3.6 in C:\Users\mkyas\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from cartopy) (3.10.8)
Requirement already satisfied: shapely>=2.0 in C:\Users\mkyas\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from cartopy) (2.1.2)
Requirement already satisfied: packaging>=21 in C:\Users\mkyas\AppData\Roaming\Python\Python314\site-packages (from cartopy) (26.0)
Collecting pyshp>=2.3 (from cartopy)
  Downloading pyshp-3.0.3-py3-none-any.whl.metadata (65 kB)
Requirement already satisfied: pyproj>=3.3.1 in C:\Users\mkyas\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from cartopy) (3.7.2)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\mkyas\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib>=3.6->cartopy) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\mkyas\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib>=3.6->cartopy) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\mkyas\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib>=3.6->cartopy) (4.62.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\mkyas\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib>=3.6->cartopy) (1.5.0)
Requirement already satisfied: pillow>=8 in C:\Users\mkyas\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib>=3.6->cartopy) (12.1.1)
Requirement already satisfied: pyparsing>=3 in C:\Users\mkyas\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from matplotlib>=3.6->cartopy) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\mkyas\AppData\Roaming\Python\Python314\site-packages (from matplotlib>=3.6->cartopy) (2.9.0.post0)
Requirement already satisfied: certifi in C:\Users\mkyas\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pyproj>=3.3.1->cartopy) (2026.2.25)
Requirement already satisfied: six>=1.5 in C:\Users\mkyas\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.7->matplotlib>=3.6->cartopy) (1.17.0)
Downloading pyshp-3.0.3-py3-none-any.whl (58 kB)
Building wheels for collected packages: cartopy
  Building wheel for cartopy (pyproject.toml): started
  Building wheel for cartopy (pyproject.toml): finished with status 'done'
  Created wheel for cartopy: filename=cartopy-0.25.0-cp314-cp314-win_amd64.whl size=11225592 sha256=8d6285fecf7d87ce200687d195be95806b258baf0b92e52b78758d7a84741014
  Stored in directory: c:\users\mkyas\appdata\local\pip\cache\wheels\db\f7\98\fd33bb00c97b064504c886694dc5d19abfa877a7ad8e8a6f39
Successfully built cartopy
Installing collected packages: pyshp, cartopy

   -------------------- ------------------- 1/2 [cartopy]
   -------------------- ------------------- 1/2 [cartopy]
   -------------------- ------------------- 1/2 [cartopy]
   -------------------- ------------------- 1/2 [cartopy]
   -------------------- ------------------- 1/2 [cartopy]
   ---------------------------------------- 2/2 [cartopy]

Successfully installed cartopy-0.25.0 pyshp-3.0.3

  WARNING: The script cartopy_feature_download.exe is installed in 'C:\Users\mkyas\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

In [ ]:
# import the libraries we need for preprocessing
from glob import glob
import pandas as pd
import numpy as np
import datetime

Import all the data from all the regions using `glob`

In [ ]:
# all the regions of interest
REGIONS = ["merseyside", "metropolitan", "thames-valley", "west-midlands"]

all_dfs = dict()

for region in REGIONS:
    # glob simply returns all the relative paths matching a certain regex
    files = glob(f"./Data/Raw/*/*{region}-street.csv")

    region_dfs = list()
    for file in files:
        # reach each csv across all sub-directories
        df = pd.read_csv(file)
        region_dfs.append(df)

    # concatenate the subdirectory dataframes into one larger region dataframe
    final_df = pd.concat(region_dfs)
    all_dfs[region] = final_df

for region in REGIONS:
    display(all_dfs[region].head(3))

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,2924710b611d2729b431c9757dc8a59b493099db0cdff3...,2024-01,Merseyside Police,Merseyside Police,-2.746819,53.389101,On or near Further/Higher Educational Building,E01012393,Halton 001B,Violence and sexual offences,Unable to prosecute suspect,NaN
1,e7a9106786b1bfe528c102865a0c037b048783a1957b4a...,2024-01,Merseyside Police,Merseyside Police,-2.746819,53.389101,On or near Further/Higher Educational Building,E01012393,Halton 001B,Violence and sexual offences,Unable to prosecute suspect,NaN
2,d46a9cbc559c43816e51d226bf804565ed477011c4faa8...,2024-01,Merseyside Police,Merseyside Police,-2.746819,53.389101,On or near Further/Higher Educational Building,E01012393,Halton 001B,Violence and sexual offences,Unable to prosecute suspect,NaN

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,e5b3ed0375b796067eb668f37a18094cce300bdbd5446c...,2024-01,Metropolitan Police Service,Metropolitan Police Service,-0.552328,50.853155,On or near Queen Street,E01031392,Arun 001C,Other theft,Unable to prosecute suspect,NaN
1,d5d46efe4a74b2fdf87f28f7c89c4d7534c80d4150f58f...,2024-01,Metropolitan Police Service,Metropolitan Police Service,-0.666558,50.848940,On or near Northfields Lane,E01031396,Arun 003D,Violence and sexual offences,Status update unavailable,NaN
2,8ee491f5ebeda54bda879fed602d2f308bfd8abf4b59f7...,2024-01,Metropolitan Police Service,Metropolitan Police Service,-0.657460,50.787270,On or near Kingsmead,E01031419,Arun 015C,Violence and sexual offences,Status update unavailable,NaN

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,d7654f1ba479644077c254538a4c4f12ab39f5341fae84...,2024-01,Thames Valley Police,Thames Valley Police,-0.692549,51.452793,On or near Winkfield Lane,E01016252,Bracknell Forest 001C,Criminal damage and arson,Unable to prosecute suspect,NaN
1,0a2cc51135bfff5c41c6d063e670555e5afc292ec00780...,2024-01,Thames Valley Police,Thames Valley Police,-0.658082,51.438484,On or near Park/Open Space,E01016252,Bracknell Forest 001C,Public order,Investigation complete; no suspect identified,NaN
2,26bfc1bb14564f58085e18da2a6f9822efb49c8627bfe3...,2024-01,Thames Valley Police,Thames Valley Police,-0.677236,51.436336,On or near Lovel Road,E01016252,Bracknell Forest 001C,Vehicle crime,Investigation complete; no suspect identified,NaN

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,NaN,2024-01,West Midlands Police,West Midlands Police,-1.849790,52.590937,On or near Walsall Road,E01009417,Birmingham 001A,Anti-social behaviour,NaN,NaN
1,NaN,2024-01,West Midlands Police,West Midlands Police,-1.840582,52.598279,On or near Badgers Bank Road,E01009418,Birmingham 001B,Anti-social behaviour,NaN,NaN
2,08fcc46d224b1e4f4065b950fa59e5251d51106f3472cd...,2024-01,West Midlands Police,West Midlands Police,-1.840582,52.598279,On or near Badgers Bank Road,E01009418,Birmingham 001B,Vehicle crime,Investigation complete; no suspect identified,NaN

In [ ]:
# understanding the types of the data
for region in REGIONS:
    print(all_dfs[region].info())
    print("-"*64)

<class 'pandas.DataFrame'>
Index: 315445 entries, 0 to 11503
Data columns (total 12 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Crime ID               283551 non-null  str
 1   Month                  315445 non-null  str
 2   Reported by            315445 non-null  str
 3   Falls within           315445 non-null  str
 4   Longitude              315445 non-null  float64
 5   Latitude               315445 non-null  float64
 6   Location               315445 non-null  str
 7   LSOA code              315445 non-null  str
 8   LSOA name              315445 non-null  str
 9   Crime type             315445 non-null  str
 10  Last outcome category  283551 non-null  str
 11  Context                0 non-null       float64
dtypes: float64(3), str(9)
memory usage: 31.3 MB
None
----------------------------------------------------------------
<class 'pandas.DataFrame'>
Index: 2366437 entries, 0 to 86691
Data columns (total 12 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Crime ID               str
 1   Month                  str
 2   Reported by            str
 3   Falls within           str
 4   Longitude              float64
 5   Latitude               float64
 6   Location               str
 7   LSOA code              str
 8   LSOA name              str
 9   Crime type             str
 10  Last outcome category  str
 11  Context                float64
dtypes: float64(3), str(9)
memory usage: 234.7 MB
None
----------------------------------------------------------------
<class 'pandas.DataFrame'>
Index: 408443 entries, 0 to 14969
Data columns (total 12 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Crime ID               366697 non-null  str
 1   Month                  408443 non-null  str
 2   Reported by            408443 non-null  str
 3   Falls within           408443 non-null  str
 4   Longitude              399558 non-null  float64
 5   Latitude               399558 non-null  float64
 6   Location               408443 non-null  str
 7   LSOA code              399558 non-null  str
 8   LSOA name              399558 non-null  str
 9   Crime type             408443 non-null  str
 10  Last outcome category  366697 non-null  str
 11  Context                0 non-null       float64
dtypes: float64(3), str(9)
memory usage: 40.5 MB
None
----------------------------------------------------------------
<class 'pandas.DataFrame'>
Index: 688744 entries, 0 to 24340
Data columns (total 12 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Crime ID               637214 non-null  str
 1   Month                  688744 non-null  str
 2   Reported by            688744 non-null  str
 3   Falls within           688744 non-null  str
 4   Longitude              688744 non-null  float64
 5   Latitude               688744 non-null  float64
 6   Location               688744 non-null  str
 7   LSOA code              688744 non-null  str
 8   LSOA name              688744 non-null  str
 9   Crime type             688744 non-null  str
 10  Last outcome category  637214 non-null  str
 11  Context                0 non-null       float64
dtypes: float64(3), str(9)
memory usage: 68.3 MB
None
----------------------------------------------------------------

The 'Month' columns is of the incorrect type `str` instead of `Date`

In [ ]:
# convert the month column to datetime
for region in REGIONS:
    all_dfs[region]["Month"] = all_dfs[region]["Month"].apply(lambda x: datetime.datetime.strptime(x, "%Y-%m"))
    all_dfs[region].info()

<class 'pandas.DataFrame'>
Index: 315445 entries, 0 to 11503
Data columns (total 12 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Crime ID               283551 non-null  str
 1   Month                  315445 non-null  datetime64[us]
 2   Reported by            315445 non-null  str
 3   Falls within           315445 non-null  str
 4   Longitude              315445 non-null  float64
 5   Latitude               315445 non-null  float64
 6   Location               315445 non-null  str
 7   LSOA code              315445 non-null  str
 8   LSOA name              315445 non-null  str
 9   Crime type             315445 non-null  str
 10  Last outcome category  283551 non-null  str
 11  Context                0 non-null       float64
dtypes: datetime64[us](1), float64(3), str(8)
memory usage: 31.3 MB
<class 'pandas.DataFrame'>
Index: 2366437 entries, 0 to 86691
Data columns (total 12 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Crime ID               str
 1   Month                  datetime64[us]
 2   Reported by            str
 3   Falls within           str
 4   Longitude              float64
 5   Latitude               float64
 6   Location               str
 7   LSOA code              str
 8   LSOA name              str
 9   Crime type             str
 10  Last outcome category  str
 11  Context                float64
dtypes: datetime64[us](1), float64(3), str(8)
memory usage: 234.7 MB
<class 'pandas.DataFrame'>
Index: 408443 entries, 0 to 14969
Data columns (total 12 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Crime ID               366697 non-null  str
 1   Month                  408443 non-null  datetime64[us]
 2   Reported by            408443 non-null  str
 3   Falls within           408443 non-null  str
 4   Longitude              399558 non-null  float64
 5   Latitude               399558 non-null  float64
 6   Location               408443 non-null  str
 7   LSOA code              399558 non-null  str
 8   LSOA name              399558 non-null  str
 9   Crime type             408443 non-null  str
 10  Last outcome category  366697 non-null  str
 11  Context                0 non-null       float64
dtypes: datetime64[us](1), float64(3), str(8)
memory usage: 40.5 MB
<class 'pandas.DataFrame'>
Index: 688744 entries, 0 to 24340
Data columns (total 12 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Crime ID               637214 non-null  str
 1   Month                  688744 non-null  datetime64[us]
 2   Reported by            688744 non-null  str
 3   Falls within           688744 non-null  str
 4   Longitude              688744 non-null  float64
 5   Latitude               688744 non-null  float64
 6   Location               688744 non-null  str
 7   LSOA code              688744 non-null  str
 8   LSOA name              688744 non-null  str
 9   Crime type             688744 non-null  str
 10  Last outcome category  637214 non-null  str
 11  Context                0 non-null       float64
dtypes: datetime64[us](1), float64(3), str(8)
memory usage: 68.3 MB

Identifying any nulls and things to fix

In [ ]:
countNull = pd.DataFrame(columns=all_dfs["merseyside"].columns) # Null count
perNull = pd.DataFrame(columns=all_dfs["merseyside"].columns)  # percentage of values that are null

for region in REGIONS:
    countNull.loc[len(countNull)] = dict(all_dfs[region].isnull().sum())
    perNull.loc[len(perNull)] = dict(all_dfs[region].isnull().mean())

In [ ]:
countNull, perNull = countNull.set_index(pd.Index(REGIONS)), perNull.set_index(pd.Index(REGIONS)) # reindex for readability
display(countNull, perNull)

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
merseyside,31894,0,0,0,0,0,0,0,0,0,31894,315445
metropolitan,483656,0,0,0,672,672,0,673,673,0,483656,2366437
thames-valley,41746,0,0,0,8885,8885,0,8885,8885,0,41746,408443
west-midlands,51530,0,0,0,0,0,0,0,0,0,51530,688744

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
merseyside,0.101108,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.101108,1.0
metropolitan,0.204382,0.0,0.0,0.0,0.000284,0.000284,0.0,0.000284,0.000284,0.0,0.204382,1.0
thames-valley,0.102208,0.0,0.0,0.0,0.021753,0.021753,0.0,0.021753,0.021753,0.0,0.102208,1.0
west-midlands,0.074817,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.074817,1.0

# Data Dictionary

| Column name     | Column Description     |
| ------------- | ------------- |
| Crime ID | Unique Identifier for each crime, is null for minor infractions|
| Month | year and month when the crime occured|
| Reported By | Police force that reported the crime |
| Falls within | Police force whose jurisdiction applied during the crime|
| Longitude | Longitude where the crime occured |
| Latitude | Latitude where the crime occured |
| Location | General descriptor of where the crime occured|
| LSOA code | Lower layer Super Output Area (LSOA) code code - smaller areas for further population analysis |
| LSOA name | Name corresponding to the LSOA code|
| Crime type | Type of offense that was committed|
| Last outcome category | Outcome of the event |
| Context | Any additional context surrounding the event |


## Updates
- Removed the Context column (all blanks)
- Removed the Location descriptor (Not necessary due to latitude and logitude provided)
- Dropped all values with unknown Latitude and Longitude (Cannot generate maps during EDA later)

In [ ]:
# dropping unneeded collumns / null values
for region in REGIONS:
    all_dfs[region] = all_dfs[region].drop(columns=["Context", "Location"])
    all_dfs[region] = all_dfs[region].dropna(subset=["Latitude", "Longitude"])
    print(all_dfs[region]["Month"].value_counts())
    display(all_dfs[region])

Month
2024-05-01    13881
2025-10-01    13572
2024-07-01    13560
2025-05-01    13553
2025-08-01    13517
2024-10-01    13459
2025-07-01    13352
2025-03-01    13096
2025-06-01    13012
2024-06-01    12944
2025-09-01    12722
2025-11-01    12637
2024-04-01    12559
2024-11-01    12551
2024-08-01    12527
2025-04-01    12471
2024-03-01    12470
2024-09-01    12415
2024-01-01    12143
2025-12-01    12066
2024-12-01    11568
2026-01-01    11504
2024-02-01    11475
2025-02-01    11199
2025-01-01    11192
Name: count, dtype: int64

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,LSOA code,LSOA name,Crime type,Last outcome category
0,2924710b611d2729b431c9757dc8a59b493099db0cdff3...,2024-01-01,Merseyside Police,Merseyside Police,-2.746819,53.389101,E01012393,Halton 001B,Violence and sexual offences,Unable to prosecute suspect
1,e7a9106786b1bfe528c102865a0c037b048783a1957b4a...,2024-01-01,Merseyside Police,Merseyside Police,-2.746819,53.389101,E01012393,Halton 001B,Violence and sexual offences,Unable to prosecute suspect
2,d46a9cbc559c43816e51d226bf804565ed477011c4faa8...,2024-01-01,Merseyside Police,Merseyside Police,-2.746819,53.389101,E01012393,Halton 001B,Violence and sexual offences,Unable to prosecute suspect
3,d4d0e467a342f73aab198be05801aab58d81a29b797751...,2024-01-01,Merseyside Police,Merseyside Police,-2.746819,53.389101,E01012393,Halton 001B,Violence and sexual offences,Unable to prosecute suspect
4,c37473887fae15811f36926c98ef841ae09f56694c9904...,2024-01-01,Merseyside Police,Merseyside Police,-2.872892,53.488785,E01006448,Knowsley 001A,Drugs,Further action is not in the public interest
...,...,...,...,...,...,...,...,...,...,...
11499,731fa77cc53d550fa72bfc331c6155b8ba5ed9708018b8...,2026-01-01,Merseyside Police,Merseyside Police,-2.966713,53.308329,E01007169,Wirral 042E,Violence and sexual offences,Under investigation
11500,bb510e830d83b1c80ac785b870b8dd641177a93f68c8d5...,2026-01-01,Merseyside Police,Merseyside Police,-2.965022,53.311884,E01007169,Wirral 042E,Violence and sexual offences,Unable to prosecute suspect
11501,d856b8b9b5473a67c45d8742613f0feb71ee3a129f5db1...,2026-01-01,Merseyside Police,Merseyside Police,-2.969782,53.309311,E01007169,Wirral 042E,Violence and sexual offences,Under investigation
11502,001fb5da1cd3d251acd43c2e933b497d3691222e178049...,2026-01-01,Merseyside Police,Merseyside Police,-2.963886,53.314752,E01007169,Wirral 042E,Violence and sexual offences,Investigation complete; no suspect identified
11503,3f018b6f8511e5caa26da962ca9b79d3fd1b11db402bf3...,2026-01-01,Merseyside Police,Merseyside Police,-2.966713,53.308329,E01007169,Wirral 042E,Other crime,Further investigation is not in the public int...

Month
2025-07-01    106677
2025-06-01    100914
2024-10-01    100785
2024-07-01    100241
2025-05-01     99386
2025-08-01     99050
2025-10-01     98545
2024-11-01     98011
2024-08-01     97529
2024-05-01     97077
2024-06-01     96735
2025-11-01     94209
2024-09-01     93981
2025-03-01     93571
2025-09-01     93280
2025-04-01     93211
2024-03-01     91591
2024-12-01     91065
2025-12-01     90961
2024-02-01     90775
2024-01-01     90739
2024-04-01     90128
2025-01-01     86952
2026-01-01     86692
2025-02-01     83660
Name: count, dtype: int64

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,LSOA code,LSOA name,Crime type,Last outcome category
0,e5b3ed0375b796067eb668f37a18094cce300bdbd5446c...,2024-01-01,Metropolitan Police Service,Metropolitan Police Service,-0.552328,50.853155,E01031392,Arun 001C,Other theft,Unable to prosecute suspect
1,d5d46efe4a74b2fdf87f28f7c89c4d7534c80d4150f58f...,2024-01-01,Metropolitan Police Service,Metropolitan Police Service,-0.666558,50.848940,E01031396,Arun 003D,Violence and sexual offences,Status update unavailable
2,8ee491f5ebeda54bda879fed602d2f308bfd8abf4b59f7...,2024-01-01,Metropolitan Police Service,Metropolitan Police Service,-0.657460,50.787270,E01031419,Arun 015C,Violence and sexual offences,Status update unavailable
3,318e91d9bd9ad081bb348b8c743236365c9178eb60229d...,2024-01-01,Metropolitan Police Service,Metropolitan Police Service,0.876815,51.147655,E01034986,Ashford 005G,Violence and sexual offences,Status update unavailable
4,8ec949bf76f02215ad73b489ff502ab32101b0834b49fc...,2024-01-01,Metropolitan Police Service,Metropolitan Police Service,0.884060,51.110654,E01034989,Ashford 010G,Violence and sexual offences,Status update unavailable
...,...,...,...,...,...,...,...,...,...,...
86687,7beb14ff5c53926b6369f70fdd921304d16c6847848336...,2026-01-01,Metropolitan Police Service,Metropolitan Police Service,-0.971273,51.406896,E01035263,Wokingham 017E,Other crime,Under investigation
86688,3a1ac798ab76f456635e961e1d75d261140c6fc8161b0b...,2026-01-01,Metropolitan Police Service,Metropolitan Police Service,-2.180323,52.576142,E01010494,Wolverhampton 028E,Public order,Under investigation
86689,6a505cd98308c586f4ef1e949898977defe8fa6a2d1f91...,2026-01-01,Metropolitan Police Service,Metropolitan Police Service,-2.218654,52.191813,E01033248,Worcester 011E,Violence and sexual offences,Under investigation
86690,d8e227ee9263712f16602bf480379d3afa33aa3038c799...,2026-01-01,Metropolitan Police Service,Metropolitan Police Service,-0.375423,50.828190,E01031799,Worthing 008C,Violence and sexual offences,Under investigation
86691,c9b80655dcb2f9a9a56cb141f259ed396b4bd92ca82f5d...,2026-01-01,Metropolitan Police Service,Metropolitan Police Service,-0.375423,50.828190,E01031799,Worthing 008C,Violence and sexual offences,Under investigation

Month
2025-07-01    18494
2024-07-01    17966
2024-06-01    17336
2025-08-01    17300
2024-05-01    17246
2024-10-01    17059
2025-06-01    16939
2024-08-01    16883
2025-05-01    16675
2025-03-01    16218
2024-04-01    15896
2024-11-01    15884
2025-09-01    15853
2024-03-01    15809
2025-10-01    15799
2025-04-01    15738
2024-09-01    15581
2025-11-01    15466
2024-01-01    15258
2024-02-01    14682
2026-01-01    14623
2024-12-01    14537
2025-01-01    14494
2025-12-01    14344
2025-02-01    13478
Name: count, dtype: int64

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,LSOA code,LSOA name,Crime type,Last outcome category
0,d7654f1ba479644077c254538a4c4f12ab39f5341fae84...,2024-01-01,Thames Valley Police,Thames Valley Police,-0.692549,51.452793,E01016252,Bracknell Forest 001C,Criminal damage and arson,Unable to prosecute suspect
1,0a2cc51135bfff5c41c6d063e670555e5afc292ec00780...,2024-01-01,Thames Valley Police,Thames Valley Police,-0.658082,51.438484,E01016252,Bracknell Forest 001C,Public order,Investigation complete; no suspect identified
2,26bfc1bb14564f58085e18da2a6f9822efb49c8627bfe3...,2024-01-01,Thames Valley Police,Thames Valley Police,-0.677236,51.436336,E01016252,Bracknell Forest 001C,Vehicle crime,Investigation complete; no suspect identified
3,f9cce6ed554d064626a11c41c5e2edd0467174f5ae397b...,2024-01-01,Thames Valley Police,Thames Valley Police,-0.674292,51.447112,E01016252,Bracknell Forest 001C,Violence and sexual offences,Action to be taken by another organisation
4,37116d29794088cdcefa2ff08f6cfd2027a8af918c13ad...,2024-01-01,Thames Valley Police,Thames Valley Police,-0.677236,51.436336,E01016252,Bracknell Forest 001C,Violence and sexual offences,Unable to prosecute suspect
...,...,...,...,...,...,...,...,...,...,...
14618,4a74ce74b3190af468cbafef9e62a89dbbf12ac40fa61c...,2026-01-01,Thames Valley Police,Thames Valley Police,-0.790772,51.376605,E01016707,Wokingham 020C,Violence and sexual offences,Unable to prosecute suspect
14619,dd1d3acbecb380ad40c1fdab8f1dd867230a3e0153753a...,2026-01-01,Thames Valley Police,Thames Valley Police,-0.824344,51.372891,E01016708,Wokingham 020D,Violence and sexual offences,Under investigation
14620,7e50962092d5f5ed5776bbb3d7b11caa4bf46fca142104...,2026-01-01,Thames Valley Police,Thames Valley Police,-0.790443,51.372735,E01016709,Wokingham 020E,Other theft,Under investigation
14621,00539d3be96085aa80ed17e71e376a580c18c536005924...,2026-01-01,Thames Valley Police,Thames Valley Police,-0.790443,51.372735,E01016709,Wokingham 020E,Other theft,Under investigation
14622,4e75d53f5e02ec5066da41e8ac94c42a2315b5ac17d64f...,2026-01-01,Thames Valley Police,Thames Valley Police,-0.790443,51.372735,E01016709,Wokingham 020E,Other crime,Under investigation

Month
2024-07-01    31636
2024-05-01    31037
2024-06-01    29865
2025-07-01    29191
2024-08-01    29180
2024-10-01    29074
2025-06-01    28708
2024-09-01    28635
2024-04-01    28495
2024-03-01    28383
2025-05-01    28292
2025-03-01    27967
2024-01-01    27500
2025-08-01    27312
2025-04-01    27296
2025-10-01    27012
2024-11-01    26571
2024-02-01    26067
2025-09-01    26066
2025-11-01    25815
2024-12-01    25723
2025-01-01    25601
2025-02-01    24624
2025-12-01    24353
2026-01-01    24341
Name: count, dtype: int64

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,LSOA code,LSOA name,Crime type,Last outcome category
0,NaN,2024-01-01,West Midlands Police,West Midlands Police,-1.849790,52.590937,E01009417,Birmingham 001A,Anti-social behaviour,NaN
1,NaN,2024-01-01,West Midlands Police,West Midlands Police,-1.840582,52.598279,E01009418,Birmingham 001B,Anti-social behaviour,NaN
2,08fcc46d224b1e4f4065b950fa59e5251d51106f3472cd...,2024-01-01,West Midlands Police,West Midlands Police,-1.840582,52.598279,E01009418,Birmingham 001B,Vehicle crime,Investigation complete; no suspect identified
3,5fc5ebcc637a23f9410af6ee90daabdaefed70fd86f93b...,2024-01-01,West Midlands Police,West Midlands Police,-1.845233,52.593943,E01009418,Birmingham 001B,Violence and sexual offences,Unable to prosecute suspect
4,5ea6fbc3cd6834f56ba25852736e3e4d53a70163f2a3a3...,2024-01-01,West Midlands Police,West Midlands Police,-1.839093,52.597818,E01009418,Birmingham 001B,Violence and sexual offences,Unable to prosecute suspect
...,...,...,...,...,...,...,...,...,...,...
24336,5b27e6da01af3a9495e72731c87d35472073edb2e97721...,2026-01-01,West Midlands Police,West Midlands Police,-2.117079,52.571358,E01034315,Wolverhampton 035J,Violence and sexual offences,Under investigation
24337,0688659bb421c0a3c24c73954f90414e460581bdc0f509...,2026-01-01,West Midlands Police,West Midlands Police,-2.117890,52.570935,E01034315,Wolverhampton 035J,Violence and sexual offences,Under investigation
24338,02e3d5273fcf16f2e2bbd900549dfb39eed960cf712bbc...,2026-01-01,West Midlands Police,West Midlands Police,-2.118019,52.569505,E01034315,Wolverhampton 035J,Violence and sexual offences,Awaiting court outcome
24339,6c560e5b41678c83f1a2736d7e2019968867b72becad31...,2026-01-01,West Midlands Police,West Midlands Police,-2.118019,52.569505,E01034315,Wolverhampton 035J,Violence and sexual offences,Unable to prosecute suspect
24340,ed4f9a2b5ac1afc744506972e35ab9c69027bd0a055213...,2026-01-01,West Midlands Police,West Midlands Police,-2.118019,52.569505,E01034315,Wolverhampton 035J,Violence and sexual offences,Local resolution

# Importing Other data (police force population data)

In [ ]:
# read csv
populationData = pd.read_csv("./Data/Raw/policeforcepopdata.csv")
# extract recent data
relevantPopData = populationData[(populationData["Year"] == 2024) & (populationData["PFA 2023 Name"].isin(["Metropolitan Police", "Thames Valley", "Merseyside", "West Midlands"]))]
# set index properly
relevantPopData = relevantPopData.set_index("PFA 2023 Name")
# drop unneeded columns
relevantPopData = relevantPopData.drop(columns=["PFA 2023 Code", "Year"])
# rename index columns rpoper;y
relevantPopData = relevantPopData.set_index(pd.Index(["metropolitan", "merseyside", "west-midlands", "thames-valley"]))

# convert each column to a proper int
for column in relevantPopData.columns:
    relevantPopData[column] = relevantPopData[column].str.replace(",", "")

# add a total columns
relevantPopData["Totals"] = relevantPopData.astype("int64").sum(axis = 1 )
display(relevantPopData)

['F0', 'F1', 'F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10', 'F11', 'F12', 'F13', 'F14', 'F15', 'F16', 'F17', 'F18', 'F19', 'F20', 'F21', 'F22', 'F23', 'F24', 'F25', 'F26', 'F27', 'F28', 'F29', 'F30', 'F31', 'F32', 'F33', 'F34', 'F35', 'F36', 'F37', 'F38', 'F39', 'F40', 'F41', 'F42', 'F43', 'F44', 'F45', 'F46', 'F47', 'F48', 'F49', 'F50', 'F51', 'F52', 'F53', 'F54', 'F55', 'F56', 'F57', 'F58', 'F59', 'F60', 'F61', 'F62', 'F63', 'F64', 'F65', 'F66', 'F67', 'F68', 'F69', 'F70', 'F71', 'F72', 'F73', 'F74', 'F75', 'F76', 'F77', 'F78', 'F79', 'F80', 'F81', 'F82', 'F83', 'F84', 'F85', 'M0', 'M1', 'M2', 'M3', 'M4', 'M5', 'M6', 'M7', 'M8', 'M9', 'M10', 'M11', 'M12', 'M13', 'M14', 'M15', 'M16', 'M17', 'M18', 'M19', 'M20', 'M21', 'M22', 'M23', 'M24', 'M25', 'M26', 'M27', 'M28', 'M29', 'M30', 'M31', 'M32', 'M33', 'M34', 'M35', 'M36', 'M37', 'M38', 'M39', 'M40', 'M41', 'M42', 'M43', 'M44', 'M45', 'M46', 'M47', 'M48', 'M49', 'M50', 'M51', 'M52', 'M53', 'M54', 'M55', 'M56', 'M57', 'M58', 'M59', 'M60', 'M61', 'M62', 'M63', 'M64', 'M65', 'M66', 'M67', 'M68', 'M69', 'M70', 'M71', 'M72', 'M73', 'M74', 'M75', 'M76', 'M77', 'M78', 'M79', 'M80', 'M81', 'M82', 'M83', 'M84', 'M85']

,F0,F1,F2,F3,F4,F5,F6,F7,F8,F9,...,M77,M78,M79,M80,M81,M82,M83,M84,M85,Totals
metropolitan,51526,51041,52918,50777,51276,50664,50846,52073,52648,51548,...,22697,17361,15658,15144,13481,11793,10164,10433,55460,9074625
merseyside,6676,7056,7612,7649,7802,7963,7957,8143,8200,8104,...,6741,4794,4386,4323,3625,3186,2835,2740,13644,1475541
west-midlands,17443,17815,18792,18337,19193,19049,19604,20246,20374,20046,...,9966,7618,7595,7429,6632,5699,4836,4750,24881,3036605
thames-valley,12969,13731,14511,14554,15016,15413,15555,16286,16422,16419,...,10483,7619,7412,7226,6252,5498,4499,4561,24932,2640201

Grouping Age population data for ease of use

In [ ]:
popDataDfs = list() # list of all dfs

# iterate over all regions
for region in REGIONS: 
    # melt dataset to get everything into 2 columns
    long = relevantPopData.loc[[region], :].melt(var_name="GenderAge", value_name="Value")

    # list of each age
    x = range(86)
    # result list
    a = list()

    # bins to split into
    bins = [0, 18, 35, 50, 65, 81, 100]

    # merging between genders for each age
    for i in range(86):
        a.append(long[(long["GenderAge"] == f"F{i}") | (long["GenderAge"] == f"M{i}")]["Value"].astype(int).sum())

    # new dataframe with age and population
    ageData = pd.DataFrame()
    ageData["Age"] = x
    ageData["Pop"] = a

    # assign each age to an age bin
    ageData["age_bin"] = pd.cut(ageData["Age"], bins=bins, labels=["0-17", "18-34", "35-49", "50-64", "65-80", "81+"], right=False)
    # group by the bins and sum them
    result = pd.DataFrame(ageData.groupby("age_bin")["Pop"].sum()).T
    popDataDfs.append(result)

# concatonate results and save
ageData = pd.concat(popDataDfs, ignore_index=True)
ageData = ageData.set_index(pd.Index(REGIONS))
ageData
ageData.to_csv("./Data/Clean/binnedAgeGroups.csv")

In [203]:
# concatonate all dfs to one single dfs to save
FINAL = pd.concat([all_dfs[region] for region in REGIONS])
FINAL.to_csv("./Data/Clean/crime-data.csv")

### Importing Outcome data (Identical process to crime data)

In [ ]:
REGIONS = ["merseyside", "metropolitan", "thames-valley", "west-midlands"]

outcomes = dict()

for region in REGIONS:
    files = glob(f"./Data/Raw/*/*{region}-outcomes.csv")

    region_dfs = list()
    for file in files:
        df = pd.read_csv(file)
        region_dfs.append(df)

    final_df = pd.concat(region_dfs)
    outcomes[region] = final_df

for region in REGIONS:
    display(outcomes[region].head(3))

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Outcome type
0,bb2c147af9059a7b4f55ca91d4ef87643ae06bec818c0b...,2024-01,Merseyside Police,Merseyside Police,-2.860304,53.434278,On or near Rosewood Close,E01006413,Knowsley 006B,Unable to prosecute suspect
1,bb2c147af9059a7b4f55ca91d4ef87643ae06bec818c0b...,2024-01,Merseyside Police,Merseyside Police,-2.860304,53.434278,On or near Rosewood Close,E01006413,Knowsley 006B,Unable to prosecute suspect
2,63bc97f12d789a8730baa5697ccb21aecabd78907da528...,2024-01,Merseyside Police,Merseyside Police,-2.860304,53.434278,On or near Rosewood Close,E01006413,Knowsley 006B,Unable to prosecute suspect

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Outcome type
0,8aa29a268193cadf610c07edf0df472968569b265d9c7b...,2024-01,Metropolitan Police Service,Metropolitan Police Service,-0.00971,51.341066,On or near Hares Bank,E01001076,Croydon 036A,Investigation complete; no suspect identified
1,0a694f873d0e4e16f4b833e4fc55bc1b12d46782faff5c...,2024-01,Metropolitan Police Service,Metropolitan Police Service,NaN,NaN,No location,NaN,NaN,Investigation complete; no suspect identified
2,6d4327ada0798f4506a9a55a46b88264da6870525a092d...,2024-01,Metropolitan Police Service,Metropolitan Police Service,NaN,NaN,No location,NaN,NaN,Investigation complete; no suspect identified

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Outcome type
0,53b0f90c163406d3d4653e5a1de6781c8581b3b12ee1c8...,2024-01,Thames Valley Police,Thames Valley Police,-1.275266,51.787036,On or near Blandford Avenue,E01028594,Oxford 001A,Unable to prosecute suspect
1,ca670c0984f334ce273b750ee6802579a05a43c54300f5...,2024-01,Thames Valley Police,Thames Valley Police,NaN,NaN,No location,NaN,NaN,Investigation complete; no suspect identified
2,deffa5a09dc6091548593b8c27c94b20a2bd8b9ba10085...,2024-01,Thames Valley Police,Thames Valley Police,NaN,NaN,No location,NaN,NaN,Suspect charged

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Outcome type
0,809b40f59f31d4f25a0fd7dac95db96358b94175500a8c...,2024-01,West Midlands Police,West Midlands Police,-1.897764,52.482804,On or near Supermarket,E01033620,Birmingham 138A,Unable to prosecute suspect
1,9219485a31fd24943267f413f223e91f2324c3a60ae870...,2024-01,West Midlands Police,West Midlands Police,-2.135100,52.616153,On or near Kyle Close,E01010502,Wolverhampton 006C,Investigation complete; no suspect identified
2,6258e1b61152e7d2c7045423b41c621bba1ac21e11130d...,2024-01,West Midlands Police,West Midlands Police,-1.942488,52.513706,On or near Farnham Road,E01009269,Birmingham 034B,Investigation complete; no suspect identified

In [5]:
for region in REGIONS:
    print(outcomes[region].info())

<class 'pandas.DataFrame'>
Index: 294526 entries, 0 to 11276
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Crime ID      294526 non-null  str
 1   Month         294526 non-null  str
 2   Reported by   294526 non-null  str
 3   Falls within  294526 non-null  str
 4   Longitude     294526 non-null  float64
 5   Latitude      294526 non-null  float64
 6   Location      294526 non-null  str
 7   LSOA code     294526 non-null  str
 8   LSOA name     294526 non-null  str
 9   Outcome type  294526 non-null  str
dtypes: float64(2), str(8)
memory usage: 24.7 MB
None
<class 'pandas.DataFrame'>
Index: 2088984 entries, 0 to 101167
Data columns (total 10 columns):
 #   Column        Dtype
---  ------        -----
 0   Crime ID      str
 1   Month         str
 2   Reported by   str
 3   Falls within  str
 4   Longitude     float64
 5   Latitude      float64
 6   Location      str
 7   LSOA code     str
 8   LSOA name     str
 9   Outcome type  str
dtypes: float64(2), str(8)
memory usage: 175.3 MB
None
<class 'pandas.DataFrame'>
Index: 356199 entries, 0 to 14048
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Crime ID      356199 non-null  str
 1   Month         356199 non-null  str
 2   Reported by   356199 non-null  str
 3   Falls within  356199 non-null  str
 4   Longitude     349157 non-null  float64
 5   Latitude      349157 non-null  float64
 6   Location      356199 non-null  str
 7   LSOA code     349157 non-null  str
 8   LSOA name     349157 non-null  str
 9   Outcome type  356199 non-null  str
dtypes: float64(2), str(8)
memory usage: 29.9 MB
None
<class 'pandas.DataFrame'>
Index: 671239 entries, 0 to 25081
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Crime ID      671239 non-null  str
 1   Month         671239 non-null  str
 2   Reported by   671239 non-null  str
 3   Falls within  671239 non-null  str
 4   Longitude     671239 non-null  float64
 5   Latitude      671239 non-null  float64
 6   Location      671239 non-null  str
 7   LSOA code     671239 non-null  str
 8   LSOA name     671239 non-null  str
 9   Outcome type  671239 non-null  str
dtypes: float64(2), str(8)
memory usage: 56.3 MB
None

In [11]:
outcomeNull = pd.DataFrame(columns=outcomes["merseyside"].columns)
outcomeNullPer = pd.DataFrame(columns=outcomes["merseyside"].columns)
for region in REGIONS:
    outcomeNull.loc[len(outcomeNull)] = dict(outcomes[region].isnull().sum())
    outcomeNullPer.loc[len(outcomeNullPer)] = dict(outcomes[region].isnull().mean())

outcomeNull, outcomeNullPer = outcomeNull.set_index(pd.Index(REGIONS)), outcomeNullPer.set_index(pd.Index(REGIONS))
display(outcomeNull, outcomeNullPer)

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Outcome type
merseyside,0,0,0,0,0,0,0,0,0,0
metropolitan,0,0,0,0,0,0,0,0,0,0
thames-valley,0,0,0,0,0,0,0,0,0,0
west-midlands,0,0,0,0,0,0,0,0,0,0

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Outcome type
merseyside,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
metropolitan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
thames-valley,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
west-midlands,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

A small minority of values have a blank longitude, latitude or LSOA. Therefore we can drop these values.

In [13]:
for region in REGIONS:
    outcomes[region] = outcomes[region].drop(columns=["Location"])
    outcomes[region] = outcomes[region].dropna(subset=["Longitude", "Latitude", "LSOA code", "LSOA name"])

In [15]:
OUTCOMES = pd.concat([outcomes[region] for region in REGIONS])
OUTCOMES.to_csv("./Data/Clean/outcomes.csv")